name: deepnewsrec
channels:
  - defaults
  - pytorch-lts
dependencies:
  - python=3.7.13
  - pytorch=1.8.2
  - cudatoolkit=10.2
  - pip
  - pip:
    - ray[tune]==2.0.0
    - mlflow==1.29.0
    - numpy==1.21.6
    - pandas==1.3.5
    - regex==2022.8.17
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - tabulate==0.8.10
    - tqdm==4.50.0
    - loguru==0.6.0
    - retrying==1.3.3
    - tensorboard==2.10.0
    - pyyaml==5.4.1
    - prettytable==3.4.1
